services:
  app:
    build: .
    container_name: todo_app
    ports:
      - "5000:5000"
    environment:
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: root
      PGDATABASE: todo_app
      PGPORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: todo_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: todo_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: todo_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
